# Impedisce il caricamento automatico dei moduli NVIDIA all'avvio
blacklist nouveau
blacklist nvidia
blacklist nvidia_uvm
blacklist nvidia_drm
blacklist nvidia_modeset

# Forza il fallimento del caricamento se non richiesto esplicitamente
install nvidia /bin/false
install nvidia_uvm /bin/false
install nvidia_drm /bin/false
install nvidia_modeset /bin/false

# Abilita il modesetting per il supporto Wayland/PRIME in Modalità Gaming
options nvidia_drm modeset=1
