# Impedisce il caricamento automatico dei moduli NVIDIA all'avvio
blacklist nouveau
blacklist nvidia
blacklist nvidia_uvm
blacklist nvidia_drm
blacklist nvidia_modeset

# Forza il fallimento del caricamento se non richiesto esplicitamente
install nvidia /bin/false
install nvidia_uvm /bin/false
install nvidia_drm /bin/false
install nvidia_modeset /bin/false

# Disabilita il display server sulla NVIDIA (Nasconde la GPU a GNOME)
alias nvidia_drm off
alias nvidia_modeset off

