# Impedisce il caricamento automatico dei moduli NVIDIA all'avvio
blacklist nvidia
blacklist nvidia_uvm

# Disabilita PERMANENTEMENTE il display server sulla NVIDIA (Nasconde la GPU a GNOME)
alias nvidia_drm off
alias nvidia_modeset off
