# AriaOS: Escludi i moduli NVIDIA e Nouveau dall'initramfs per caricamento on-demand
omit_drivers+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm nouveau "
install_items+=" /etc/modprobe.d/blacklist-nvidia.conf "
