# NixitOS: Escludi i moduli NVIDIA dall'initramfs per caricamento on-demand
omit_dracutmodules+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm "
install_items+=" /etc/modprobe.d/blacklist-nvidia.conf "
